/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional information regarding
 * copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package net.gcolin.rest.ext.datasource;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.activation.DataSource;

/**
 * A DataSource generated by DataSourceProvider.
 * 
 * @author Gaël COLIN
 * @since 1.0
 */
public class SimpleDataSource implements DataSource {

  private String contentType;
  private String name;
  private InputStream inputStream;

  /**
   * Create a read only data source.
   * 
   * @param contentType the type of data source
   * @param name the name of data source
   * @param inputStream an input stream
   */
  public SimpleDataSource(String contentType, String name, InputStream inputStream) {
    this.contentType = contentType;
    this.name = name;
    this.inputStream = inputStream;
  }

  @Override
  public String getContentType() {
    return contentType;
  }

  @Override
  public InputStream getInputStream() throws IOException {
    return inputStream;
  }

  @Override
  public String getName() {
    return name;
  }

  @Override
  public OutputStream getOutputStream() throws IOException {
    throw new IOException("cannot do this");
  }

}
